# Usar uma imagem do Node.js como base
FROM node:18-alpine

# Definir diretório de trabalho
WORKDIR /app

# Copiar arquivos essenciais primeiro
COPY package.json package-lock.json ./
RUN npm install

# Copiar todos os arquivos do backend para o container
COPY . /app

# Definir o diretório de trabalho para a pasta correta
WORKDIR /app/api

# Expor a porta usada pelo backend
EXPOSE 3001

# Comando para rodar o backend dentro de /api
CMD ["node", "server.js"]